using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

namespace BandoWare.GameplayTags.Editor.Config
{
   internal static class GameplayTagConfigCodeGenerator
   {
      private const string k_GeneratorVersion = "1.0";

      // Updates the given file with wrapper code generated for the given action sets.
      // If the generated code is unchanged, does not touch the file.
      // Returns true if the file was touched, false otherwise.
      public static bool WriteGeneratedConfigClass(GameplayTagConfigData configData)
      {
         string filePath = configData.GeneratedClassPath;

         // Validate that the file is located within the Assets folder
         if (!filePath.ToLower().StartsWith("assets/") &&
             !filePath.ToLower().StartsWith("assets\\"))
         {
            filePath = Path.Combine("Assets", filePath);
         }

         // Validate directory
         string dir = Path.GetDirectoryName(filePath);
         if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
         {
            Directory.CreateDirectory(dir);
         }

         if (!Path.HasExtension(filePath))
         {
            filePath += ".cs";
         }

         // Generate class code
         string code = GenerateCodeFile(configData);

         // Check if the code changed. Don't write if it hasn't
         if (File.Exists(filePath))
         {
            string existingCode = File.ReadAllText(filePath);
            if (existingCode == code /*|| StripAllWhitespace(existingCode) == StripAllWhitespace(code)*/)
            {
               return false;
            }
         }

         // Write to file
         //EditorHelpers.CheckOut(filePath); // TODO: Check if this is necessary?
         File.WriteAllText(filePath, code);
         AssetDatabase.Refresh();
         return true;
      }

      private static string StripAllWhitespace(string str)
      {
         StringBuilder buffer = new();
         foreach (char ch in str)
         {
            if (!char.IsWhiteSpace(ch))
            {
               buffer.Append(ch);
            }
         }
         return buffer.ToString();
      }

      private static string GenerateCodeFile(GameplayTagConfigData configData)
      {
         string rootClassName = !string.IsNullOrEmpty(configData.GeneratedClassName) ? configData.GeneratedClassName : "AllGameplayTags";
         string classNamespace = !string.IsNullOrEmpty(configData.GeneratedClassNamespace) ? configData.GeneratedClassNamespace : "BandoWare.GameplayTags";

         // Initialize dictionary for storing the hierarchical structure of tags
         TagNode rootTag = new(rootClassName);

         // Build code file as string
         StringBuilder sourceBuilder = new();

         // Auto-generated notice
         sourceBuilder.AppendLine("//------------------------------------------------------------------------------");
         sourceBuilder.AppendLine("// <auto-generated>");
         sourceBuilder.AppendLine("//     This code was auto-generated by com.bandoware.gameplaytags:" + nameof(GameplayTagConfigCodeGenerator));
         sourceBuilder.AppendLine("//     Version " + k_GeneratorVersion);
         sourceBuilder.AppendLine();
         sourceBuilder.AppendLine("//     Changes to this file may be lost if the code is regenerated and could cause incorrect behavior.");
         sourceBuilder.AppendLine("// </auto-generated>");
         sourceBuilder.AppendLine("//------------------------------------------------------------------------------");

         // Includes and namespace
         sourceBuilder.AppendLine();
         sourceBuilder.AppendLine("using BandoWare.GameplayTags;");
         sourceBuilder.AppendLine();
         sourceBuilder.AppendLine("namespace " + classNamespace);
         sourceBuilder.AppendLine("{");

         string indent1 = new('\t', 1);
         string indent2 = new('\t', 2);
         string indent3 = new('\t', 3);

         // Outer class with GameplayTagConfigBase inheritance
         sourceBuilder.AppendLine($"{indent1}/// <summary>");
         sourceBuilder.AppendLine($"{indent1}/// Class containing all GameplayTags defined for the current project.");
         sourceBuilder.AppendLine($"{indent1}/// Changes should be performed via the GameplayTags Project Settings.");
         sourceBuilder.AppendLine($"{indent1}/// </summary>");
         sourceBuilder.AppendLine($"{indent1}public partial class {rootClassName} : {nameof(GameplayTagConfigBase)}");
         sourceBuilder.AppendLine($"{indent1}{{");

         // TagDefinitionEntry value arrays
         sourceBuilder.AppendLine($"{indent2}/// All GameplayTag definitions for the current project, ordered alphabetically.");
         sourceBuilder.AppendLine($"{indent2}private readonly {nameof(TagDefinitionEntry)}[] m_GameplayTagDefinitionEntries =");
         sourceBuilder.AppendLine($"{indent2}{{");
         foreach (TagDefinitionEntry definitionEntry in configData.TagDefinitionEntries)
         {
            sourceBuilder.AppendLine($"{indent3}new(\"{definitionEntry.tagName}\", \"{definitionEntry.description}\"),");
            // Add each GameplayTag defined via the config to the tag hierarchy 
            AddTagToHierarchy(rootTag, definitionEntry.tagName);
         }
         sourceBuilder.AppendLine($"{indent2}}};");
         sourceBuilder.AppendLine();

         // TagRenameEntry value arrays
         sourceBuilder.AppendLine($"{indent2}/// A record of renamed GameplayTags in chronological order, mapping old to new names.");
         sourceBuilder.AppendLine($"{indent2}private readonly {nameof(TagRenameEntry)}[] m_GameplayTagRenameEntries =");
         sourceBuilder.AppendLine($"{indent2}{{");
         foreach (TagRenameEntry renameEntry in configData.TagRenameEntries)
         {
            sourceBuilder.AppendLine($"{indent3}new(\"{renameEntry.oldTagName}\", \"{renameEntry.newTagName}\"),");
         }
         sourceBuilder.AppendLine($"{indent2}}};");
         sourceBuilder.AppendLine();

         // TagDefinitionEntry and TagRenameEntry value getters
         sourceBuilder.AppendLine($"{indent2}public override {nameof(TagDefinitionEntry)}[] {nameof(GameplayTagConfigBase.GetGameplayTagDefinitionEntries)}() => m_GameplayTagDefinitionEntries;");
         sourceBuilder.AppendLine($"{indent2}public override {nameof(TagRenameEntry)}[] {nameof(GameplayTagConfigBase.GetGameplayTagsRenameEntries)}() => m_GameplayTagRenameEntries;");
         sourceBuilder.AppendLine();

         // Start generating code from the root node
         sourceBuilder.AppendLine($"{indent2}//--------------------------------------------------------------------------------------------------------------");
         sourceBuilder.AppendLine($"{indent2}// All defined GameplayTags as hierarchical structure of classes below:");
         sourceBuilder.AppendLine($"{indent2}//--------------------------------------------------------------------------------------------------------------");
         GenerateTagClasses(sourceBuilder, rootClassName, rootTag, 1);

         // Close namespace scope
         sourceBuilder.AppendLine("}");

         // Return finished code as string
         return sourceBuilder.ToString();
      }

      private static void AddTagToHierarchy(TagNode root, string tag)
      {
         string[] parts = tag.Split('.');
         TagNode currentNode = root;

         foreach (string part in parts)
         {
            if (part == "Tag")
               break;

            if (!currentNode.Children.ContainsKey(part))
            {
               currentNode.Children[part] = new TagNode(part, currentNode);
            }

            currentNode = currentNode.Children[part];
         }
      }

      private static void GenerateTagClasses(StringBuilder sourceBuilder, string rootClassName, TagNode node, int indentLevel)
      {
         string indent = new('\t', indentLevel);

         if (node.Name != rootClassName)
         {
            if (indentLevel > 2)
            {
               sourceBuilder.AppendLine();
            }

            sourceBuilder.AppendLine($"{indent}public static class {node.Name}");
            sourceBuilder.AppendLine($"{indent}{{");
            string tagPath = string.Join(".", GetTagPath(rootClassName, node));
            sourceBuilder.AppendLine($"{indent}\tprivate static readonly GameplayTag s_Tag = GameplayTagManager.RequestTag(\"{tagPath}\");");
            sourceBuilder.AppendLine($"{indent}\tpublic static GameplayTag Get() {{ return s_Tag; }}");
         }

         indentLevel++;

         foreach (TagNode childNode in node.Children.Values)
         {
            GenerateTagClasses(sourceBuilder, rootClassName, childNode, indentLevel);
         }

         sourceBuilder.AppendLine(new string('\t', indentLevel - 1) + "}");
      }

      private static IEnumerable<string> GetTagPath(string rootClassName, TagNode node)
      {
         Stack<string> path = new();
         TagNode current = node;

         while (current != null && current.Name != rootClassName)
         {
            path.Push(current.Name);
            current = current.Parent;
         }

         return path;
      }

      private class TagNode
      {
         public string Name { get; }
         public TagNode Parent { get; set; }
         public Dictionary<string, TagNode> Children { get; }

         public TagNode(string name, TagNode parent = null)
         {
            Name = name;
            Parent = parent;
            Children = new Dictionary<string, TagNode>();
         }
      }
   }
}